support webp file
daxingplay/css-combo pull request #33
Opened 2023-05-11 12:49 UTC by jianjiade

支持webp文件类型

2023-05-11 16:24 UTC, daxingplay requested changes

2023-05-11 16:24 UTC, daxingplay commented on README.md
> +# forked from daxingplay/css-combo
这个建议去掉吧

2023-05-11 16:24 UTC, daxingplay commented on package.json
这个文件可以只改版本号

2023-05-12 09:31 UTC, jianjiade commented on package.json
已经去除了

2023-05-13 14:59 UTC, daxingplay approved these changes
LGTM

2023-05-13 15:00 UTC, merged